name: Feature Request
description: Request a feature to be added to the engine.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, Please don't ask for anything that's super difficult to do.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
        - Feature that would make the game more enjoyable
    validations:
      required: true
